const VolunteerJobsReverse = [
    { 
        id: 1, 
        title: 'YNOTFORTOTS Volunteer Tutor', 
        company: 'YNOTFORTOTS', 
        location: 'Vancouver', 
        type: 'In-Person', 
        logo: ''
        },
    { 
        id: 2, 
        title: 'Wildlife Rescue Association of BC', 
        company: 'Wildlife Rescue Association of BC', 
        location: 'BC', 
        type: 'Virtual', 
        logo: ''
    },
    {
        id: 3,
        title: 'Volunteer with Shelter Movers',
        company: 'Shelter Movers',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 4,
        title: 'Volunteer Drivers for Food Deliveries',
        company: 'Refood Food Rescue Foundation',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 5,
        title: 'Vancouver Emergency Management Agency',
        company: 'Vancouver Emergency Management Agency',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 6,
        title: 'UBC Third World Eye Care Society',
        company: 'UBC Third World Eye Care Society',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 7,
        title: 'UBC SPIHC Volunteer',
        company: 'UBC Students for Partners in Health Canada',
        location: 'Anywhere',
        type: 'On Campus',
        logo: '',
    },
    {
        id: 8,
        title: 'UBC Red Cross Club Volunteer',
        company: 'UBC Red Cross Club',
        location: 'Vancouver',
        type: 'On Campus',
        logo: '',
    },
    {
        id: 9,
        title: 'UBC Music for Mentak Health',
        company: 'UBC Music for Mentak Health',
        location: 'UBC',
        type: 'On Campus',
        logo: '',
    },
    {
        id: 10,
        title: 'UBC Mental Health Awareness Club Volunteer',
        company: 'UBC Mental Health Awareness Club',
        location: 'Vancouver',
        type: 'On Campus',
        logo: '',
    },
    {
        id: 11,
        title: 'UBC HSF Volunteer',
        company: 'UBC Heart and Stroke Foundation',
        location: 'Vancouver',
        type: 'On Campus',
        logo: '',
    },
    {
        id: 12,
        title: 'UBC Blood for Life Volunteer',
        company: 'UBC Blood for Life',
        location: 'Vancouver',
        type: 'On Campus',
        logo: '',
    },
    {
        id: 13,
        title: 'The Reading Bear Society Volunteer',
        company: 'The Reading Bear',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 14,
        title: 'Swim Drink Fish Volunteer',
        company: 'Swim Drink Fish',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 15,
        title: 'Stanley Park Ecology Society',
        company: 'Stanley Park Ecology Society',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 16,
        title: 'School Breakfast Volunteer',
        company: 'Breakfast Club of Canada',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 17,
        title: 'Public Education Volunteer',
        company: 'Seniors First BC',
        location: 'Vancouver',
        type: 'Off Campus, Virtual',
        logo: '',
    },
    {
        id: 18,
        title: 'Peer Support Program Volunteer',
        company: 'MS Society of Canada',
        location: 'Anywhere',
        type: 'Virtual',
        logo: '',
    },
    {
        id: 19,
        title: 'Mentors for Indigenous Youth',
        company: 'Urban Native Youth Association',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 20,
        title: 'Learning Buddies Network',
        company: 'Learning Buddies Network',
        location: 'Greater Vancouver',
        type: 'Off Campus, Virtual',
        logo: '',
    },
    {
        id: 21,
        title: 'Lead Inbstructor',
        company: 'Canada Learning Code',
        location: 'Vancouver',
        type: 'Off Campus, Virtual',
        logo: '',
    },
    {
        id: 22,
        title: 'KidSafe Volunteer',
        company: 'KidSafe Project Society',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 23,
        title: 'Habitat for Humanity Volunteer',
        company: 'Habitat for Humanity Greater Vancouver',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 24,
        title: 'Growing Chefs Volunteer',
        company: 'Growing Chefs',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 25,
        title: 'Greater Vancouver Food Bank Volunteer',
        company: 'Greater Vancouver Food Bank',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 26,
        title: 'Girls to the Power of Math Volunteer',
        company: 'Girls to the Power of Math',
        location: 'Anywhere',
        type: 'Off Campus, Virtual',
        logo: '',
    },
    {
        id: 27,
        title: 'Fraser Health Crisis Line',
        company: 'Fraser Health Crisis Line',
        location: 'Surrey',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 28,
        title: 'Digital Learning Assistant Volunteer',
        company: 'MOSAIC',
        location: 'Anywhere',
        type: 'Off Campus, Virtual',
        logo: '',
    },
    {
        id: 29,
        title: 'CUBS Volunteer',
        company: 'CUBS',
        location: 'Vancouver',
        type: 'Off Campus, Virtual',
        logo: '',
    },
    {
        id: 30,
        title: 'CityReach Care Society Volunteer',
        company: 'CityReach Care Society',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 31,
        title: 'Cassie + Friends Volunteer',
        company: 'Cassie and Friends',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 32,
        title: 'Canuck Place Volunteer',
        company: 'Canuck Place',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 33,
        title: 'Canadian Blood Services Volunteer',
        company: 'Canadian Blood Services',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    {
        id: 34,
        title: 'Big Brothers of Greater Vancouver',
        company: 'Big Brothers of Greater Vancouver',
        location: 'Vancouver',
        type: 'Off Campus, Virtual',
        logo: '',
    },
    {
        id: 35,
        title: 'Ask An Undergrad',
        company: 'Ask An Undergrad',
        location: 'Canada',
        type: 'Virtual',
        logo: '',
    },
    {
        id: 36,
        title: 'AIDS Vancouver Volunteer',
        company: 'AIDS Vancouver',
        location: 'Vancouver',
        type: 'Off Campus',
        logo: '',
    },
    // More jobs…
    ];

export const checkBoxesList = 
            [ {
                "id": 1,
                "name": "Off Campus"
            },
            {
                "id": 2,
                "name": "On Campus"
            },
            {
                "id": 3,
                "name": "Virtual"
            },
        ]

    export const VolunteerJobs = VolunteerJobsReverse.reverse();