const VolunteerJobsReverse = [
    { 
        id: 1, 
        title: 'YNOTFORTOTS Volunteer Tutor', 
        company: 'YNOTFORTOTS', 
        location: 'Vancouver', 
        type: 'In-Person', 
        link: 'http://ynotfortots.com/give/',
        logo: ''
        },
    { 
        id: 2, 
        title: 'Wildlife Rescue Association of BC', 
        company: 'Wildlife Rescue Association of BC', 
        location: 'BC', 
        type: 'Virtual',
        link: 'https://www.wildliferescue.ca/what-we-do/volunteering/', 
        logo: ''
    },
    {
        id: 3,
        title: 'Volunteer with Shelter Movers',
        company: 'Shelter Movers',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://www.sheltermovers.com/volunteer/',
        logo: '',
    },
    {
        id: 4,
        title: 'Volunteer Drivers for Food Deliveries',
        company: 'Refood Food Rescue Foundation',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'www.refood.ca',
        logo: '',
    },
    {
        id: 5,
        title: 'Vancouver Emergency Management Agency',
        company: 'Vancouver Emergency Management Agency',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://vancouver.ca/home-property-development/emergency-social-services.aspx',
        logo: '',
    },
    {
        id: 6,
        title: 'UBC Third World Eye Care Society',
        company: 'UBC Third World Eye Care Society',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://www.instagram.com/ubctwecs/',
        logo: '',
    },
    {
        id: 7,
        title: 'UBC SPIHC Volunteer',
        company: 'UBC Students for Partners in Health Canada',
        location: 'Anywhere',
        type: 'On Campus',
        link: 'https://www.facebook.com/ubcspihc/',
        logo: '',
    },
    {
        id: 8,
        title: 'UBC Red Cross Club Volunteer',
        company: 'UBC Red Cross Club',
        location: 'Vancouver',
        type: 'On Campus',
        link: 'https://www.facebook.com/ubcredcross/',
        logo: '',
    },
    {
        id: 9,
        title: 'UBC Music for Mental Health',
        company: 'UBC Music for Mental Health',
        location: 'UBC',
        type: 'On Campus',
        link: 'https://www.campusgroups.com/product/home/',
        logo: '',
    },
    {
        id: 10,
        title: 'UBC Mental Health Awareness Club Volunteer',
        company: 'UBC Mental Health Awareness Club',
        location: 'Vancouver',
        type: 'On Campus',
        link: 'https://www.facebook.com/UBCMHAC',
        logo: '',
    },
    {
        id: 11,
        title: 'UBC HSF Volunteer',
        company: 'UBC Heart and Stroke Foundation',
        location: 'Vancouver',
        type: 'On Campus',
        link: 'https://www.facebook.com/ubcHSFclub',
        logo: '',
    },
    {
        id: 12,
        title: 'UBC Blood for Life Volunteer',
        company: 'UBC Blood for Life',
        location: 'Vancouver',
        type: 'On Campus',
        link: 'https://www.facebook.com/ubcbloodclub/',
        logo: '',
    },
    {
        id: 13,
        title: 'The Reading Bear Society Volunteer',
        company: 'The Reading Bear',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://thereadingbear.ca/volunteer-info',
        logo: '',
    },
    {
        id: 14,
        title: 'Swim Drink Fish Volunteer',
        company: 'Swim Drink Fish',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://www.swimdrinkfish.ca/volunteer',
        logo: '',
    },
    {
        id: 15,
        title: 'Stanley Park Ecology Society',
        company: 'Stanley Park Ecology Society',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://stanleyparkecology.ca/about/volunteer/',
        logo: '',
    },
    {
        id: 16,
        title: 'School Breakfast Volunteer',
        company: 'Breakfast Club of Canada',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://www.breakfastclubcanada.org/the-cause/volunteers/',
        logo: '',
    },
    {
        id: 17,
        title: 'Public Education Volunteer',
        company: 'Seniors First BC',
        location: 'Vancouver',
        type: 'Off Campus, Virtual',
        link: 'https://seniorsfirstbc.ca/get-involved/volunteer/',
        logo: '',
    },
    {
        id: 18,
        title: 'Peer Support Program Volunteer',
        company: 'MS Society of Canada',
        location: 'Anywhere',
        type: 'Virtual',
        link: 'https://mscanada.ca/volunteer',
        logo: '',
    },
    {
        id: 19,
        title: 'Mentors for Indigenous Youth',
        company: 'Urban Native Youth Association',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://unya.bc.ca/get-involved/#volunteer',
        logo: '',
    },
    {
        id: 20,
        title: 'Learning Buddies Network',
        company: 'Learning Buddies Network',
        location: 'Greater Vancouver',
        type: 'Off Campus, Virtual',
        link: 'https://www.learningbuddiesnetwork.com/',
        logo: '',
    },
    {
        id: 21,
        title: 'Lead Instructor',
        company: 'Canada Learning Code',
        location: 'Vancouver',
        type: 'Off Campus, Virtual',
        link: 'https://www.canadalearningcode.ca/volunteer/',
        logo: '',
    },
    {
        id: 22,
        title: 'KidSafe Volunteer',
        company: 'KidSafe Project Society',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://www.kidsafe.ca/volunteer-1',
        logo: '',
    },
    {
        id: 23,
        title: 'Habitat for Humanity Volunteer',
        company: 'Habitat for Humanity Greater Vancouver',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://www.habitatgv.ca/event-team-volunteer',
        logo: '',
    },
    {
        id: 24,
        title: 'Growing Chefs Volunteer',
        company: 'Growing Chefs',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://www.growingchefs.ca/volunteer-with-us/',
        logo: '',
    },
    {
        id: 25,
        title: 'Greater Vancouver Food Bank Volunteer',
        company: 'Greater Vancouver Food Bank',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://foodbank.bc.ca/volunteer/group-volunteers/',
        logo: '',
    },
    {
        id: 26,
        title: 'Girls to the Power of Math Volunteer',
        company: 'Girls to the Power of Math',
        location: 'Anywhere',
        type: 'Off Campus, Virtual',
        link: 'https://www.girlstothepowerofmath.org/',
        logo: '',
    },
    {
        id: 27,
        title: 'Fraser Health Crisis Line',
        company: 'Fraser Health Crisis Line',
        location: 'Surrey',
        type: 'Off Campus',
        link: 'https://www.options.bc.ca/volunteer-at-options',
        logo: '',
    },
    {
        id: 28,
        title: 'Digital Learning Assistant Volunteer',
        company: 'MOSAIC',
        location: 'Anywhere',
        type: 'Off Campus, Virtual',
        link: 'https://mosaicbc.org/volunteer/',
        logo: '',
    },
    {
        id: 29,
        title: 'CUBS Volunteer',
        company: 'CUBS',
        location: 'Vancouver',
        type: 'Off Campus, Virtual',
        link: 'https://docs.google.com/forms/d/e/1FAIpQLSdQH9kV2WT-bGD40xpG32tH72lxc27PnxnLyfFCH1Z41que7g/viewform',
        logo: '',
    },
    {
        id: 30,
        title: 'CityReach Care Society Volunteer',
        company: 'CityReach Care Society',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://app.betterimpact.com/Application?OrganizationGuid=dbf7d941-802a-4c48-a688-b582a407365b&ApplicationFormNumber=1',
        logo: '',
    },
    {
        id: 31,
        title: 'Cassie + Friends Volunteer',
        company: 'Cassie and Friends',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://cassieandfriends.ca/volunteer/',
        logo: '',
    },
    {
        id: 32,
        title: 'Canuck Place Volunteer',
        company: 'Canuck Place',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://www.canuckplace.org/how-to-give/volunteer/',
        logo: '',
    },
    {
        id: 33,
        title: 'Canadian Blood Services Volunteer',
        company: 'Canadian Blood Services',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://app.betterimpact.com/PublicEnterprise/EnterpriseSearch?EnterpriseGuid=0b68e364-95da-420a-891c-bda9ba835ea4&SearchType=Organization&SearchId=29387',
        logo: '',
    },
    {
        id: 34,
        title: 'Big Brothers of Greater Vancouver',
        company: 'Big Brothers of Greater Vancouver',
        location: 'Vancouver',
        type: 'Off Campus, Virtual',
        link: 'https://www.bigbrothersvancouver.com/',
        logo: '',
    },
    {
        id: 35,
        title: 'Ask An Undergrad',
        company: 'Ask An Undergrad',
        location: 'Canada',
        type: 'Virtual',
        link: 'https://www.askanundergrad.com/',
        logo: '',
    },
    {
        id: 36,
        title: 'AIDS Vancouver Volunteer',
        company: 'Ribbon Community',
        location: 'Vancouver',
        type: 'Off Campus',
        link: 'https://app.betterimpact.com/Application?OrganizationGuid=f480a80e-8cec-4d3d-a1d2-a585383f00a1&ApplicationFormNumber=1',
        logo: '', 
    },
];

export const VolunteerJobs = VolunteerJobsReverse.reverse();